=== Bee926/yearn-meta/schema/strategy.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strategy.json",
  "title": "Strategy",
  "description": "A Yearn strategy",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "authorUri": {
      "type": "string",
      "format": "uri"
    },
    "media": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": ["name", "description"]
}

=== Bee926/yearn-meta/data/strategies/LPProfitSwitching.json
{
  "$schema": "strategy",
  "name": "LPProfitSwitching",
  "description": "Earn is a lending aggregator that strives to attain the highest yield for supported coins (DAI, USDC, USDT, TUSD, sUSD, or wBTC) at all times. It does this by programmatically shifting these coins between several lending protocols (AAVE, dYdX, and Compound) operating on the Ethereum blockchain.",
  "author": "unknown",
  "authorUri": "https://twitter.com/"
}

=== Bee926/yearn-meta/data/strategies/StrategyAH2Earncy.json
{
  "$schema": "strategy",
  "name": "StrategyAH2Earncy",
  "description": "Lends {{tokens}} on Alpha Homora v2 to generate interest. Users of Alpha Homora borrow {{tokens}} to perform leveraged yield-farming on Alpha\u2019s platform.",
  "author": "unknown",
  "authorUri": "https://twitter.com/"
}

=== Bee926/yearn-meta/data/strategies/StrategyIdle.json
{
  "$schema": "strategy",
  "name": "StrategyIdle",
  "description": "This strategy supplies {{tokens}} on IDLE.finance to farm COMP and IDLE. Rewards are harvested, sold for more {{tokens}}, and deposited back to the vault.",
  "author": "Emiliano Bonassi",
  "authorUri": "https://twitter.com/emilianobonassi"
}
